export let faculties = {
    'Administración de Empresas y Contabilidad': 0,
    'Administración Pública': 0,
    'Arquitectura y Diseño': 0,
    'Bellas Artes': 0,
    'Ciencias Agropecuarias': 0,
    'Ciencias de la Educación': 0,
    'Ciencias Naturales': 0,
    'Comunicación Social': 0,
    'Derecho y Ciencias Políticas': 0,
    'Economía': 0,
    'Enfermería': 0,
    'Farmacia': 0,
    'Humanidades': 0,
    'Informática': 0,
    'Ingeniería': 0,
    'Medicina': 0,
    'Medicina Veterinaria': 0,
    'Odontología': 0,
    'Psicología': 0,
};